### ISSUE TITLE
Establish naming conventions for piquassoboost

### ISSUE THREAD

**Issue by icnots** [Budapest-Quantum-Computing-Group/piquassoboost#41]
* Aggre on namings convention like `camelCase` and `PascalCase` or `snake_case`... (e.g.: `GaussianState_Cov::ConvertToComplexAmplitudes`, `GaussianState_Cov::getReducedGaussianState`, `GaussianState_Cov::get_representation`, `GaussianState_Cov::Update_covariance_matrix`)
* naming conventions of matrix datatypes should be agreed on (`pic::matrix`, `matrix32`, `matrix_real`, `matrix_real16`)
* `matrix_base::isnan` method rename: `contains_nan` or `has_nan`
* Other possible changes..

**Comment by rakytap** [comment]
Is this still an open issue?
