### ISSUE TITLE
Torontonian code

### ISSUE THREAD

**Issue by nquesada** [Budapest-Quantum-Computing-Group/piquassoboost#55]
In https://arxiv.org/pdf/2109.04528.pdf the authors state "The developed recursive Torontonian algorithm is going to be shipped as a part of a larger photonic quantum computer simulation package [45]". Has the new Torontonian algorithm been integrated into the library?

**Comment by rakytap** [comment]
Dear nquesada!  Sorry for the delayed response! Until now we did not paid much attention to the list of issues. I just noticed your question right now, which means we would need to check the reported issues on regular basis. The implementation of the Torontonian algorithm can be found in files piquassoboost/sampling/source/TorontonianRecursive.*, and piquassoboost/sampling/source/TorontonianUtilities.*

If you have any other question or feedback please feel free to contact us.

**Comment by nquesada** [comment]
Thanks! No worries. This great to know!
